"""
Medical Context Generator Module

Generates educational medical context for health screening results.
Non-decisional - provides general information, NOT clinical advice.
"""
from dataclasses import dataclass, field
from typing import Dict, Any, List, Optional
from enum import Enum

from app.core.extraction.base import PhysiologicalSystem
from app.core.inference.risk_engine import RiskLevel
from app.core.llm.gemini_client import GeminiClient, GeminiConfig
from app.config import settings
from app.utils import get_logger

logger = get_logger(__name__)


@dataclass
class MedicalContext:
    """Educational medical context for a physiological system."""
    system: PhysiologicalSystem
    
    # Educational content
    system_overview: str = ""
    biomarker_explanations: Dict[str, str] = field(default_factory=dict)
    risk_level_meaning: str = ""
    general_health_info: str = ""
    
    # Lifestyle factors
    lifestyle_factors: List[str] = field(default_factory=list)
    
    # When to seek care
    warning_signs: List[str] = field(default_factory=list)
    
    # Metadata
    is_mock: bool = False
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "system": self.system.value,
            "system_overview": self.system_overview,
            "biomarker_explanations": self.biomarker_explanations,
            "risk_level_meaning": self.risk_level_meaning,
            "general_health_info": self.general_health_info,
            "lifestyle_factors": self.lifestyle_factors,
            "warning_signs": self.warning_signs,
            "is_mock": self.is_mock
        }


class MedicalContextGenerator:
    """
    Generates educational medical context using LLM.
    
    NON-DECISIONAL: Provides general health education, not medical advice.
    """
    
    # Pre-defined context for each system (fallback/cache)
    SYSTEM_OVERVIEWS = {
        PhysiologicalSystem.CNS: (
            "The central nervous system (CNS) controls body movement, coordination, "
            "and cognitive functions. Screening indicators include gait patterns, "
            "posture stability, and tremor characteristics."
        ),
        PhysiologicalSystem.CARDIOVASCULAR: (
            "The cardiovascular system circulates blood throughout the body. "
            "Key indicators include heart rate, heart rate variability (HRV), "
            "and blood pressure measurements."
        ),

        PhysiologicalSystem.GASTROINTESTINAL: (
            "The gastrointestinal system processes food and absorbs nutrients. "
            "Abdominal motion patterns and respiratory coupling provide indirect "
            "indicators of GI function."
        ),
        PhysiologicalSystem.SKELETAL: (
            "The skeletal system provides structure and enables movement. "
            "Gait analysis, joint mobility, and posture metrics indicate "
            "musculoskeletal health."
        ),
        PhysiologicalSystem.SKIN: (
            "The skin is the body's largest organ, providing protection and "
            "temperature regulation. Visual analysis can detect texture, "
            "color, and surface characteristics."
        ),
        PhysiologicalSystem.EYES: (
            "The eyes provide vision and reflect overall neurological health. "
            "Blink patterns, gaze stability, and pupil responses are measurable "
            "indicators."
        ),
        PhysiologicalSystem.NASAL: (
            "The nasal and respiratory system enables oxygen exchange. "
            "Breathing patterns, rate, and regularity indicate respiratory health."
        ),
        PhysiologicalSystem.REPRODUCTIVE: (
            "Reproductive health indicators are assessed through autonomic "
            "proxies, as direct non-invasive measurement is limited. "
            "These are indirect indicators only."
        ),
        PhysiologicalSystem.PULMONARY: (
            "The pulmonary system handles gas exchange in the lungs. "
            "Breathing rate, tidal volume patterns, and SpO2 trends "
            "are key non-invasive screening markers."
        ),
    }

    # Static general health info — previously generated by LLM on every call.
    # Content is identical for every patient with the same system, so a static
    # dict eliminates an unnecessary Gemini API call with zero quality loss.
    GENERAL_HEALTH_INFO = {
        PhysiologicalSystem.CNS: (
            "Adequate sleep (7-9 hours), regular aerobic exercise, cognitive stimulation "
            "such as reading or puzzles, and social engagement all support long-term brain "
            "and nervous system health. Stress management is also key."
        ),
        PhysiologicalSystem.CARDIOVASCULAR: (
            "Regular aerobic exercise (≥150 min/week), a balanced diet low in saturated "
            "fat and sodium, maintaining a healthy weight, not smoking, and managing stress "
            "are the core pillars of cardiovascular health."
        ),
        PhysiologicalSystem.GASTROINTESTINAL: (
            "A high-fibre diet with plenty of fruits and vegetables, staying well hydrated, "
            "eating at regular intervals, and limiting processed foods and alcohol support "
            "healthy digestion and gut motility."
        ),
        PhysiologicalSystem.SKELETAL: (
            "Weight-bearing exercise, adequate calcium (1000-1200 mg/day) and vitamin D, "
            "maintaining good posture, and avoiding prolonged sedentary periods protect "
            "bone density and joint health."
        ),
        PhysiologicalSystem.SKIN: (
            "Daily sun protection (SPF 30+), staying hydrated, a nutrient-rich diet, "
            "regular self-examination for new or changing lesions, and avoiding smoking "
            "are key to maintaining skin integrity."
        ),
        PhysiologicalSystem.EYES: (
            "Annual eye examinations, the 20-20-20 rule for screen users (every 20 min, "
            "look 20 feet away for 20 seconds), UV-protective eyewear outdoors, and a "
            "diet rich in lutein and omega-3s support ocular health."
        ),
        PhysiologicalSystem.NASAL: (
            "Avoiding smoke and airborne irritants, regular aerobic exercise to build "
            "lung capacity, maintaining indoor air quality with plants or air purifiers, "
            "and practising diaphragmatic breathing exercises support respiratory function."
        ),
        PhysiologicalSystem.REPRODUCTIVE: (
            "Regular health screenings, stress management (which directly influences "
            "hormonal balance), a balanced diet, sufficient sleep, and open communication "
            "with a healthcare provider underpin reproductive and hormonal health."
        ),
        PhysiologicalSystem.PULMONARY: (
            "Avoiding smoke and airborne pollutants, regular aerobic exercise to build "
            "lung capacity, maintaining indoor air quality, practising deep-breathing "
            "exercises, and getting recommended vaccinations (e.g., flu, pneumonia) all "
            "support long-term pulmonary health."
        ),
    }
    
    RISK_LEVEL_MEANINGS = {
        RiskLevel.LOW: (
            "A LOW risk level indicates that measured parameters are within "
            "expected normal ranges. Continue current health practices."
        ),
        RiskLevel.MODERATE: (
            "A MODERATE risk level suggests some parameters warrant attention. "
            "Consider discussing with a healthcare provider."
        ),
        RiskLevel.HIGH: (
            "A HIGH risk level indicates parameters that require attention. "
            "Consultation with a healthcare professional is recommended."
        ),
        RiskLevel.ACTION_REQUIRED: (
            "An ACTION_REQUIRED risk level indicates significant abnormalities. "
            "Prompt medical evaluation is strongly recommended."
        ),
        RiskLevel.UNKNOWN: (
            "The risk level could not be determined from the available data. "
            "Further assessment or data collection may be required."
        ),
    }
    
    SYSTEM_INSTRUCTION = """You are a medical education assistant providing general health information.

CONSTRAINTS:
1. Provide EDUCATIONAL information only, NOT medical advice
2. Do NOT diagnose or suggest specific conditions
3. Do NOT recommend specific treatments
4. Always recommend consulting healthcare professionals
5. Use accessible language for general audiences

Your role is to help people understand what their screening results mean in general terms."""
    
    def __init__(self, client: Optional[GeminiClient] = None):
        """Initialize context generator."""
        if client is None:
            # Use settings for API configuration
            config = GeminiConfig(
                api_key=settings.gemini_api_key,
                model=settings.gemini_model
            )
            self.client = GeminiClient(config)
        else:
            self.client = client
        self._generation_count = 0
        logger.info("MedicalContextGenerator initialized")
    
    def generate_context(
        self,
        system: PhysiologicalSystem,
        risk_level: RiskLevel,
        biomarkers: Optional[List[str]] = None,
        use_llm: bool = True   # kept for API compatibility; LLM no longer used here
    ) -> MedicalContext:
        """
        Generate medical context for a physiological system.

        All educational content is now served from pre-built static dictionaries,
        eliminating an unnecessary Gemini API call per request.  The `use_llm`
        parameter is retained for backward compatibility but has no effect.
        """
        context = MedicalContext(system=system)

        # Populate all fields from static sources — zero API calls
        context.system_overview = self.SYSTEM_OVERVIEWS.get(system, "")
        context.risk_level_meaning = self.RISK_LEVEL_MEANINGS.get(risk_level, "")
        context.general_health_info = self.GENERAL_HEALTH_INFO.get(
            system,
            "Maintain a healthy lifestyle and attend regular medical check-ups."
        )
        context.lifestyle_factors = self._get_lifestyle_factors(system)
        context.warning_signs = self._get_warning_signs(system, risk_level)
        context.biomarker_explanations = self._get_biomarker_explanations(system, biomarkers)
        context.is_mock = False   # static data is real, not mock

        self._generation_count += 1
        return context
    
    # _enhance_with_llm removed: the general health info it generated is identical
    # for every patient sharing the same physiological system. It is now served
    # from the GENERAL_HEALTH_INFO dict above, saving one Gemini API call per
    # context-generation request with zero reduction in content quality.

    
    def _get_lifestyle_factors(self, system: PhysiologicalSystem) -> List[str]:
        """Get general lifestyle factors for a system."""
        factors = {
            PhysiologicalSystem.CNS: [
                "Regular physical activity supports brain health",
                "Quality sleep is essential for cognitive function",
                "Mental stimulation helps maintain neural connections"
            ],
            PhysiologicalSystem.CARDIOVASCULAR: [
                "Regular aerobic exercise strengthens the heart",
                "A balanced diet supports cardiovascular health",
                "Stress management benefits heart function"
            ],

            PhysiologicalSystem.GASTROINTESTINAL: [
                "A fiber-rich diet supports digestive health",
                "Regular meal patterns aid digestion",
                "Staying hydrated helps GI function"
            ],
            PhysiologicalSystem.SKELETAL: [
                "Weight-bearing exercise builds bone strength",
                "Adequate calcium and vitamin D intake",
                "Good posture reduces strain"
            ],
            PhysiologicalSystem.SKIN: [
                "Sun protection prevents skin damage",
                "Hydration and nutrition affect skin health",
                "Regular self-examination for changes"
            ],
            PhysiologicalSystem.EYES: [
                "Regular eye exams are important",
                "Screen breaks reduce eye strain",
                "Protective eyewear when appropriate"
            ],
            PhysiologicalSystem.NASAL: [
                "Avoiding irritants protects airways",
                "Regular exercise supports lung capacity",
                "Good air quality benefits breathing"
            ],
            PhysiologicalSystem.REPRODUCTIVE: [
                "Regular health screenings are important",
                "Stress management affects hormonal balance",
                "Healthy lifestyle supports overall function"
            ],
        }
        return factors.get(system, ["Maintain a healthy lifestyle", "Regular medical checkups"])
    
    def _get_warning_signs(self, system: PhysiologicalSystem, risk_level: RiskLevel) -> List[str]:
        """Get warning signs that warrant medical attention."""
        if risk_level == RiskLevel.LOW:
            return ["Seek care if you experience any concerning symptoms"]
        
        general = ["Consult a healthcare provider if symptoms persist"]
        
        specific = {
            PhysiologicalSystem.CNS: [
                "Sudden balance or coordination problems",
                "Unexplained tremors or weakness",
                "Confusion or cognitive changes"
            ],
            PhysiologicalSystem.CARDIOVASCULAR: [
                "Chest pain or discomfort",
                "Shortness of breath at rest",
                "Irregular heartbeat",
                "Unexplained fatigue"
            ],

        }
        
        return specific.get(system, general)
    
    def _get_biomarker_explanations(
        self,
        system: PhysiologicalSystem,
        biomarkers: Optional[List[str]]
    ) -> Dict[str, str]:
        """Get cached biomarker explanations."""
        explanations = {
            "heart_rate": "Heart rate measures the number of heartbeats per minute",
            "hrv_rmssd": "Heart rate variability indicates the variation between heartbeats",
            "gait_variability": "Gait variability measures consistency in walking patterns",
            "posture_entropy": "Posture entropy reflects the complexity of balance control",
            "respiratory_rate": "Respiratory rate is the number of breaths per minute",
            "blink_rate": "Blink rate indicates eye comfort and neurological function",
            "gait_symmetry_ratio": "Gait symmetry compares left and right step patterns",
        }
        
        if not biomarkers:
            return {}
        
        return {bm: explanations.get(bm, f"{bm} is a measured health indicator") for bm in biomarkers}
